const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSU5ySDBNb3B4QkZTVlVoM0Y1cVNxREtEdEdNZTN2UmZSYTVtbEQwNlNsZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaTdnUk1MZ3VLVU5sWitjejhpVnBZa2toKzZjYlg4WDJJSjZTeERhR2VVUT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI2SHhnMEtFbmdhNVlPWWpWUmc1bUZVQmw1dXJyK1ZhaEl1UlFLc0VlM21BPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJhaHdMTEFXeEtIWVd1RGcyVjJWcWxFTTFPYk5JNmdNT3ZDYTI1c0RxckEwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjhIalE5QWExQzV5S0tPektRZHRVNkpISHJxQUVBcWZwRVdXbmE1MFFvbXc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IncvOW1ZRUp4RU5KK2E2d0o5aG91MnMzamZaWGZzSVpJZzRkU2M2cE9BVVU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTUNRaG5BViticlZWR3Q2WldoZll5U3lBeXNuWTJjS2pLeUJ1RjgvOXhsUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiM2VrRVVuZkJrdDhHWE5nZ0p1d1AxbU5hSVZLY0h3QnJRNGMyZGQ1MDR6ND0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImxUbWYxcE9QeWhCY0VVQzl0RVV2Uk5MeU1BZUlsQ2lRQmVHNkRnbERyRXZyTmVwZHEwdTZMQ2tRREdtVVE1RVBYUmtwb0htVkJJbE5BL0QyUmsxTkFBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTE5LCJhZHZTZWNyZXRLZXkiOiJNNFplRHViWkwzZVNkazM5YWIzdlJ3UXFWcWJoZkRhSzBxRmpWT2pNWkd3PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6ZmFsc2UsImFjY291bnQiOnsiZGV0YWlscyI6IkNLdjhyNDRKRUx2aWdzNEdHQU1nQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJYcFRUNElwMThvODk2UGhQUGxKNU1BRTVFaVZUWHR1SzhuOGpvNFFTZzBrPSIsImFjY291bnRTaWduYXR1cmUiOiIwVlRBNXh5UDF2SlNvVXpTT29FczZRZUpZQXRxUTV6TFNMK3JQcFdqbVBoQjBFZ3BrMHJPZ1NZU3c0ejJEc2FiUEUvZmtDeEZ6VXBsdnYzeFEvc1BpZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiWnF0aTN6VDgwOG5GRm1jVG94SFVYS2R3YzVsRzU2U2hkMEpxbk82WkpjakgvYktYemJDQU9rbkdQRGlYeWI0M2lkU0F0Z2JBQ005cGhKbWlXQUFBQXc9PSJ9LCJtZSI6eyJpZCI6IjIzNDkxMzU2ODM3ODg6ODhAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiIxMDI5NjMzMTgxNDkzNjk6ODhAbGlkIn0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjIzNDkxMzU2ODM3ODg6ODhAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCVjZVMCtDS2RmS1BQZWo0VHo1U2VUQUJPUklsVTE3Yml2Si9JNk9FRW9OSiJ9fV0sInBsYXRmb3JtIjoiaXBob25lIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQklJRFFnQyJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NzQyMzU5NzIsImxhc3RQcm9wSGFzaCI6Im5tM0JiIiwibXlBcHBTdGF0ZUtleUlkIjoiQUZZQUFLeGsifQ==",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
